name: "Pull request checks"
on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3

      - name: "Changes filter"
        uses: dorny/paths-filter@v2.11.0
        id: changes
        with:
          filters: |
            src:
              - "Cargo.toml"
              - "src/**"

      - name: "Add clippy component"
        if: steps.changes.outputs.src == 'true'
        uses: actions-rs/toolchain@v1.0.7
        with:
            toolchain: stable
            components: clippy
            override: true

      - name: "Do clippy check"
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: "Build"
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --verbose